### ISSUE TITLE
what is this 40.0 magic number?

### ISSUE THREAD

**Issue by mreinstein** [johnBuffer/VerletSFML-Multithread#4]
Looking at this line in physics_object.hpp:

```c++
const Vec2 new_position = position + last_update_move + (acceleration - last_update_move * 40.0f) * (dt * dt);
```

https://github.com/johnBuffer/VerletSFML-Multithread/blob/4c380909f5fe02b0acb4904581737e5d66d96c0d/src/physics/physic_object.hpp#L32C9-L32C119

**Comment by johnBuffer** [comment]
It's an arbitray value used to damp velocity (it's a rough approximation of air friction).
